### ISSUE TITLE
Live Graphics Application 1.2.7.4 Issues

### ISSUE THREAD

**Issue by LPcafe** [unitedworldwrestling/arena-public#1]
In previous version 1.2.2.1 UWW-LGTV used LT (Lower Third as screenshot below), which controlled with the Score Board app (UWW Timing).
With last version UWW-LGTV (1.2.7.4) with new 1080 TV broadcast design and new Protocol (2.0) everything works correctly (include UWW Timing 1.2), except LT (as screenshot below) - they are no longer controlled (from UWW Timing) and displayed at all in graphics. How now to manage triggering these LTs (in on-screen TV GFX) from Score Board app (UWW Timing) or via external software tools (from OB VAN for example) ?????
TV Key mode (TV Fill/TV Key) support hardware alpha keying with Blackmagic output cards (DeckLink 4K Extreme 12G or DeckLink Duo 2 for example), if support, why are TV Fill and TV Key installed separately?
What is Delay (+ or -) feature in last version UWW-LGTV (1.2.7.4) ????
Is there any Help (manual) or FAQ for new features for UWW-LGTV (1.2.7.4), Live Graphics on OBS Software.pdf doc absolutely useless now ???

![LT multi](https://user-images.githubusercontent.com/71815045/94130543-7cf7fb80-fe65-11ea-8390-eee51ca87fb1.jpg)

**Comment by bouaziz1991** [comment]
Hello @LPcafe

> With last version UWW-LGTV (1.2.7.4) with new 1080 TV broadcast design and new Protocol (2.0) everything works correctly (include UWW Timing 1.2), except LT (as screenshot below) - they are no longer controlled (from UWW Timing) and displayed at all in graphics. How now to manage triggering these LTs (in on-screen TV GFX) from Score Board app (UWW Timing) or via external software tools (from OB VAN for example) ?????

**This is a bug will be fixed in next version, thank you for your feedback ;)**

> TV Key mode (TV Fill/TV Key) support hardware alpha keying with Blackmagic output cards (DeckLink 4K Extreme 12G or DeckLink Duo 2 for example), if support, why are TV Fill and TV Key installed separately?

**LGTV need to be run in two devices, one need to run on Key mode and the other in Fill mode, then these two feeds will be send to OB VAN or any production system, it's not an Alpha Keying app, it's a double feeds app (Key&Fill)**

> What is Delay (+ or -) feature in last version UWW-LGTV (1.2.7.4) ????

**In some events, we got a delay between Scoreboard TV and LGTV (On camera view) that's why I add a delay configuration to keep the Scoreboard TV synchronized with LGTV.**

> Is there any Help (manual) or FAQ for new features for UWW-LGTV (1.2.7.4), Live Graphics on OBS Software.pdf doc absolutely useless now ???

**The pdf manual will be uptadet as soon these bugs will be fixed, feel free to write us an Issue in this Github repository and we will answer fastly as possible.**

Thank you @LPcafe again for your feedback.

**Comment by wrestlinguww** [comment]
can you send the download link for latest version of LGTV. best regards

**Comment by LPcafe** [comment]
Yes, please send the download link for me

**Comment by csabavirag** [comment]
The new version has not been released yet. You will get it through the built-in automatic update (it checks for new versions at launch), but we will also update the README document of this GitHub repository, as well as https://arena.uww.io webpage.

Hopefully you will get it soon.
