### ISSUE TITLE
Support of "round-robin" tournament types with 2 possible losses 

### ISSUE THREAD

**Issue by delros** [unitedworldwrestling/arena-public#123]
**Which application you are interested about**
Arena

Hi team, 

I would like to double-check the possibility to support the event type which is not kind of a full "Round-Robin", but works in a pretty similar manner considering only 2 possible losses. As far as I can see, this is not possible to set up, at least with the current version of Arena, is this correct? If so, wondering if this feature might be somewhere in your backlog already by chance or not. 

Will be good to have clarity here, since as of now we need to find out and consider alternative tools or software to organize the tournament, but in any case, "Arena" is "industry-standard" here, so trying to rely on it as much as possible :)

Thanks,
Ernesto

**Comment by csabavirag** [comment]
If I understand you well, you would like to organize a Round Robin group type event between athletes, but instead of competing every athlete against the others, if somebody looses two times, it stops there and will participate in no further matches.
So the pairing can be determined only in first 2 rounds then it needs to be re-calculated due to the fallen out athletes.  

If so, unfortunately Arena does not support such a competition format at the moment.

If I remember well, similar method has been used long-long time ago especially in young age categories. If that's the requirement, I would recommend to consider the "Double Bracket" mode where more people get change for repechage (in Double Bracket mode, the opponents of the 1/2 finals will be considered as repechage participants - vs Single Bracket where only the Finalists' opponents will go to repechage. So in Double Bracket mode, 2x more athlete can have a change to achieve bronze medal than in Single Bracket mode)
