### ISSUE TITLE
Balkan Wrestling

### ISSUE THREAD

**Issue by prosfygas33** [unitedworldwrestling/arena-public#125]
Arena

**Your question**
Hello, I would like to ask aboUt balkan wrestling championship U15-U17 which will take place in Greece. My question is when i create a new event what type of event I should categorize this championship?

**Comment by csabavirag** [comment]
I would recommend to chose 'International Tournament'.

The different event types selected in Arena impact the UI templates in LGTV, so you can get different colour schemes in TV graphics if you change the event type from one to another. 
On Arena side, the only side effect is that if you chose World Championships, you will only see the team name on the fight list at Sessions tab instead of the Athlete's name + team name.
