### ISSUE TITLE
Determine the number of successful and unsuccessful challenges during the competition

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#162]
Hello, dear Mr.Csaba
Due to storing the challenges performed during the competitions in the system, is it possible to determine the number of successful and unsuccessful challenges during a competition from the system, please help.

**Comment by csabavirag** [comment]
Hi Mostafa,

have you tried the /referee portal? There is a Challenge Report menu where you can see all the challenges registered for a competition.
If you manage your Referees, this report will also include them. Otherwise you can see the statuses in the "Final Decision" column.
To easily create a summary of challenge statuses, use "Download full report in XLSX" and can calculate the result there.

### Screenshot of Challenge Report:
![image](https://github.com/unitedworldwrestling/arena-public/assets/10976654/4d35b10d-1ef0-4c04-b089-1771e894f9fc)

**Comment by mostafaaghayari** [comment]
Thank you very much.
