### ISSUE TITLE
Lacks the ability to automatically assign judges from additional regions

### ISSUE THREAD

**Issue by AlexeyTatarin** [unitedworldwrestling/arena-public#168]
Good afternoon!
The current version of Arena (1.5.94.2) lacks the ability to automatically assign judges from additional regions. 

First, I upload a list of athletes (in the example, there are 9), 

<img width="716" alt="Снимок экрана 2024-05-24 130402" src="https://github.com/unitedworldwrestling/arena-public/assets/96054940/961c38ac-4409-4b5e-b738-aa09aef6ddbd">

but when adding a referee I cannot create exceptions for already added regions.

<img width="947" alt="Снимок экрана 2024-05-24 125214" src="https://github.com/unitedworldwrestling/arena-public/assets/96054940/a6bb99b1-9681-4472-b4e9-062adf7b6757">

**Desktop (please complete the following information):**
 - OS: [e.g. Windows 11]
 - Browser [Firefox browser]
 - Version [126.0]

**Comment by csabavirag** [comment]
You would like to include or exclude a referee from assignment based on their team membership (Country/Team and Origins)?
Because the base rule in Arena is to compare the fight's Athletes' team with the referee Team (+ defined Origins) and not to assign the referee if those are the same. So you can only exclude a referee from assignment. That also means, if the referee's Country+Origins do not match with the athletes' team, then the referee will be part of the proposal.

That's true, the application only accepts Origins based on the ISO Country list (which is the case on UWW managed events) and does not look up in existing team names different from ISO Countries. Which is your case, since you are using your own non-country based team list.

There has not been such a request to extend the origin list to

**Comment by AlexeyTatarin** [comment]
Recently, the Arena has been very actively used for national championships in our country, and in the future for competitions at the regional level. 

It would be very convenient to assign judges in automatic mode, because in this case the assignment is even and it is possible to analyze how successful each judge was at Challenges. 

This data will allow to evaluate the work of the judging committee and to form a rating of judges.

Is it possible to make changes to the algorithm of automatic assignment of judges? (additional regions, not included in ISO
 countries)

**Comment by csabavirag** [comment]
Let us analyse the existing solution and see how we could extend the Origin attribute to accept Teams already added to the event.

Please note, if you want to define "regions", it will not work, because athletes do not have the region preference. They only have their Team what we can use to match with the referees' Team/Origin list for exclusion. So instead of using "regions", you would have to list all the teams in those regions under the Origin attribute of the referee.

**Comment by AlexeyTatarin** [comment]
Unfortunately, any attempt to list teams under the referee's Origin attribute remains unsuccessful. 

Please advise how to implement this in the ARENA workflow

**Comment by csabavirag** [comment]
Give us some time to extend the origin to the teams of an event.

**Comment by AlexeyTatarin** [comment]
Great news!!!

**Comment by csabavirag** [comment]
This feature has been added to Arena version 1.5.96.
You have 2 options to set Referee Origins:
1. Editing referees one-by-one and set their origin
2. via Referee import XLS

In both cases a Team must exist under the event to be able to set as an Origin for the referee. Un-existing teams under the Origin column in the import XLS will be discarded.
Thus it's recommended to add/import athletes first (this will create all their teams automatically), then edit/import referees.

![image](https://github.com/unitedworldwrestling/arena-public/assets/10976654/fd4dc2f9-c5d0-45f6-a513-7f5596d5dce6)

**Comment by AlexeyTatarin** [comment]
Thank you so much! There will be some starts in September, I will definitely test this option and post how it works
