### ISSUE TITLE
Error displaying results

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#173]
Hello dear csaba. As you can see, some of the menus related to team matches are not displayed correctly, please check.

https://github.com/unitedworldwrestling/arena-public/assets/82810245/2cde0154-e4f9-45e4-97a1-93dcd18a0756

**Comment by csabavirag** [comment]
On the sessions tab your video did not show the status of the Finals session. However before that, I would note that you only have 1 pool (Pool A), which is not the recommended practice for team competition in Arena.
In order to be able to organize the finals, you must have 2 pools (exactly).

So the Team competition looks like:
Round Robin between teams in Pool A and B
Then you can generate the finals, which will be organized as:
Final 1-2: between # 1 in Pool A and B
Final 3-4: between # 2 in Pool A and B 
Final 5-6: between # 3 in Pool A and B

if you don't follow this logic, Arena might produce unexpected results.

**Comment by mostafaaghayari** [comment]
Dear Mr. CSABA, as you can see, two groups have been formed, but still the final result and some of the menus are not displayed. 

https://github.com/unitedworldwrestling/arena-public/assets/82810245/e2659234-5a46-4622-b9b6-c8e643353dea

**Comment by csabavirag** [comment]
A fix to the error on Complete results has been deployed as part of Arena version 1.5.96

**Comment by mostafaaghayari** [comment]
Thank
