### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Artem19qq** [unitedworldwrestling/arena-public#191]
hello!
can i ask you about this problem? what is it?
![питання](https://github.com/user-attachments/assets/46163c91-6bf5-4c51-804a-6bb9d22c8e94)

**Comment by csabavirag** [comment]
On your screenshot, it's not clear if the errors are about `u15` or `u16`. I assume it's `u16` which is not a UWW standard Audience (age category).
If you go to Settings->Sports Config, you can see the currently available Audience - Style - Weight category definitions available in Arena by default. You must use those categories in your import XLS file, otherwise if there is no such a weight category setup, Arena will display these errors to you after import.

![image](https://github.com/user-attachments/assets/32fbaf5a-9865-43a2-be0f-38a95b366b7e)

If you have weight categories different from the UWW standard ones, you can create those by your own under the Sports Config menu. Either by cloning an existing weight with all their attributes or defining new ones and setting them up manually.

**Comment by Artem19qq** [comment]
I need add U-16 age category!

пн, 28 жовт. 2024 р. о 11:32 csabavirag ***@***.***> пише:

**Comment by Artem19qq** [comment]
thank you very much, I understood where the error was, everything worked out
