### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by Artem19qq** [unitedworldwrestling/arena-public#192]
Hello! How to set up the scoreboard? where to find information?

**Comment by Artem19qq** [comment]
Good morning! I can't choose Network interface. whats wrong?
![scoreboard](https://github.com/user-attachments/assets/853682a8-4d03-4418-94e7-eb6e5e61ee15)

**Comment by Artem19qq** [comment]
which network interface to choose?
![Знімок екрана 2024-10-31 104919](https://github.com/user-attachments/assets/6e8daefc-e526-42d8-aac2-8c88f559be7e)

**Comment by palvespt** [comment]
Hello @Artem19qq 

The Arena URL is the target computer (the one that has the Arena competition running).

The network interface is the computer with the scroeborad app. Here you need to select the IP address of the computer with the scoreborad app. 

In case you have 2 networks adapters you will have to choose the one that is working (connected).

Hope it helps.

**Comment by csabavirag** [comment]
I would say `192.168.1.129`, that looks like the most as a local network IP address.
In order to chose the right network interface, first you must know how your computer is connected to your local network (cable or Wifi). Then based on this connection type, you can find the appropriate interface on the list.

You can even run `route print` command in Terminal/Command Prompt and have to look for the `Interface` value on the row, where the `Network Destination` is `0.0.0.0`

```
...
IPv4 Route Table
===========================================================================
Active Routes:
Network Destination        Netmask          Gateway       Interface  Metric
          0.0.0.0          0.0.0.0      192.168.1.1    192.168.1.146     40 <=== This is the default network interface which must be set in Scoreboard
        127.0.0.0        255.0.0.0         On-link         127.0.0.1    331
...
```

**Comment by Artem19qq** [comment]
![ip config](https://github.com/user-attachments/assets/e942e741-d70d-457f-b6ab-0ebf2cb9b489)

**Comment by csabavirag** [comment]
and you can access your Arena via http://192.168.1.181:8080 from this computer?
If yes, I would recommend to use Auto Discovery where you must enter your Arena admin username and password. Scoreboard will try to fetch further connection parameters from Arena via 192.168.1.181:8080.
Then Load matches must work (unless there are no matches in that Arena at all :) )

**Comment by Artem19qq** [comment]
I want to use the scoreboard on another computer. it is not there Arena.

**Comment by Artem19qq** [comment]
On another laptop use only uwwtiming

**Comment by Artem19qq** [comment]
error: invalid Arena Creditentials.
Where to find this data?

**Comment by mostafaaghayari** [comment]
Hello, dear friends

https://github.com/user-attachments/assets/4ea442d0-29e9-48f3-a596-6efdc5610b74

**Comment by csabavirag** [comment]
As the video points on that, you must put the IP address of Arena server into Scoreboard's settings window.

So if you have the following setup:
```
Scoreboard laptop (IP: 192.168.1.x) ----> Arena laptop (IP: 192.168.1.y)
```
Then you must set the `Arena API URL` as http://192.168.1.**y**:8080
If you click on `Auto Discovery` button underneath the `Arena API URL` input box, you must provide the same username and password what you use when accessing http://192.168.1.y:8080/bracket Since you can configure multiple users with different roles on Arena, here in scoreboard you must use an Arena user credentials with ADMIN role (for example the very first user you created on Arena after you installed it).

To ensure the connectivity between Scoreboard laptop and Arena laptop, launch a web browser on Scoreboard laptop and navigate to http://192.168.1.y/bracket (Arena laptop). If you can successfully login to arena from Scoreboard laptop, that means these two laptops can reach each other over your network.

**Comment by Artem19qq** [comment]
Thank you all! the scoreboard started working!
