### ISSUE TITLE
Alish rules

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#194]
Hello, Mr. csaba
In the provided rules of Alish, there is only one third place. However, in the Arena program, there are two third places. Please advise.

![01](https://github.com/user-attachments/assets/323fc65d-d2cc-438a-a9ea-2da4b198743b)
![02](https://github.com/user-attachments/assets/ab4ed297-8ff6-41ca-9c0b-e396c5e67f18)

**Comment by csabavirag** [comment]
Hello Mostafa, since 2nd half of 2023 Alish and other traditional styles had overhaul last year, therefore this style applies repechage, as well as 2 rounds of Final 3-5.
See the last 2023 World Combat Games results at https://arena.uww.org/sport-event/show/1ee70e2e-42a9-67a2-bf37-bf979106bd4f as example
 
I asked internally to follow up and get the most recent Rules Book published at uww.org

**Comment by mostafaaghayari** [comment]
I appreciate your guidance and follow-up very much.
