### ISSUE TITLE
[Arena] Beach Wrestling ARENA Bug

### ISSUE THREAD

**Issue by mikeyrus** [unitedworldwrestling/arena-public#2]
ARENA 1.5.53 or 1.5.49

Getting an "500 Internal Server Error" when clicking "Create matches" on a "Session" menu on a Beach wrestling competition mode.
Number of athletes in one weight is different: 4, 6, 7 or 8. The same result everytime.

![1-draw](https://user-images.githubusercontent.com/73798069/97815527-bb23de80-1c9f-11eb-94a2-cbc263a9ee61.png)
![2-session](https://user-images.githubusercontent.com/73798069/97815528-bc550b80-1c9f-11eb-9637-52dd3683196b.png)
![3-error](https://user-images.githubusercontent.com/73798069/97815530-bc550b80-1c9f-11eb-91a4-713e9e8887f9.png)

OS: Win 10
Browser: Firefox 82.0.2 (64 bit) and Chrome 86.0.4240.111 (64 bit)

**Comment by csabavirag** [comment]
The 2nd screenshot indicates, you hit a known bug. No date and time was set on sessions at event creation, so the session tabs only show "All days | Day 1 | Day 2" **without** the dates, instead of like "All days | Day 1 (Sat 31-Oct) | Day 2 (Sun 1-Nov)".

Just click on the `Edit` button from the `Results | Add mat | Edit | Program` command bar and set the start/end dates for your session. Repeat it for all your sessions.
For example:
Session | Start | End
-------- | ----- | ---
Day 1 - Morning - Round 1 | 31-Oct-2020 10:00 | 31-Oct-2020 13:00
Day 1 - Afternoon - Round 2 | 31-Oct-2020 15:00 | 31-Oct-2020 18:00
Day 2 - Morning - Round 3 | 1-Nov-2020 10:00 | 1-Nov-2020 13:00
... | ... | ...

Then you will be able to create matches.

**Comment by csabavirag** [comment]
Closing as the fix is available in the next version after 1.5.53.
