### ISSUE TITLE
Wrong Ranking criteria for the Nordic tournament

### ISSUE THREAD

**Issue by kirodeniro** [unitedworldwrestling/arena-public#20]
**Which application you are experiencing a problem with**
[Arena]

**Describe the bug**
According to the latest Regulations (February 2021) in article 8, the Ranking criteria for the Nordic tournament is as follows:
".....In the Nordic tournament, the wrestler with the highest number of victories will be ranked first.
----> In the same group, if two wrestlers have an equal number of victories, their direct match will determine the
ranking....."
In Arena is used previous (old) criteria. See attached picture

**Expected behavior**
Correct ranking when two athletes have the same number of victories.

**Screenshots**
![Nordix](https://user-images.githubusercontent.com/15437873/112848872-32c03300-90b1-11eb-9b35-4f4c03a89ef3.jpg)

**Comment by csabavirag** [comment]
What is your Arena version?

**Comment by kirodeniro** [comment]
Arena 1.5.70.1На 29.03.2021 г. 17:57 ч. csabavirag ***@***.***> написа:
What is your Arena version?

**Comment by csabavirag** [comment]
I tested your bracket (with different names, but same results) and Arena manages the tie properly according to the 2021 rules.
I've made test with different versions of Arena, and prior to Arena version 1.5.71 the bracket is generated similar to your screenshot. However starting from version 1.5.71, athlete A5 is considered as winner.

I can conclude 2 things:
1. You are running on earlier version of Arena (which should not be the case, since you confirmed your version as 1.5.70.1)
2. Your event is set up with a start/end date prior to 01-Feb-2021. Since the new rules were announced in February, any event organised before Feb-2021 is calculated based on the previous rule set. The new rules are only used for events after 31st of January.

[2021_rule_1.5.70.2.pdf](https://github.com/unitedworldwrestling/arena-public/files/6228817/2021_rule_1.5.70.2.pdf)
[2021_rule_1.5.71.pdf](https://github.com/unitedworldwrestling/arena-public/files/6228818/2021_rule_1.5.71.pdf)
[2021_rule_1.5.71.1.pdf](https://github.com/unitedworldwrestling/arena-public/files/6228820/2021_rule_1.5.71.1.pdf)
[2021_rule_1.5.72.pdf](https://github.com/unitedworldwrestling/arena-public/files/6228823/2021_rule_1.5.72.pdf)
And if the event's startdate is changed back to 03-Jan-2021 under 1.5.72
[2021_rule_1.5.72_beforeFebruary.pdf](https://github.com/unitedworldwrestling/arena-public/files/6228826/2021_rule_1.5.72_beforeFebruary.pdf)
