### ISSUE TITLE
Is it necessary to stop synchronising an event when it has been ended?

### ISSUE THREAD

**Issue by futaz** [unitedworldwrestling/arena-public#21]
**Which application you are interested about**
Arena

**Your question**
We have three Arena instances. One master which is public on the internet and two client to be used on sport events locally.

The events are created and configured on master instance, then synchronized to one of the clients before the actual event.
During the events we pause the sync due to lack of internet connection. After the event, we turn the sync function on, so then we have all the event's data on both the master and client instance.

According to your [webinar](https://uww.org/webinar/arena-training-series-arena-advanced-feature-part-ii) the sync should be turned off afterwards.

My question is that it is really necessary to turn off the sync on the settings page of the event on the client instance? Has it any side effect if we leave the sync on?

It isn't uncommon that our staff has to do corrections in the data late after the event and it will be nice to have these modifications on both instances (master & client). This is why we would like to leave the sync on.

**Comment by csabavirag** [comment]
The only reason why we recommend to turn off sync once the event is completed and the sync buffer is flushed is to avoid accidental changed happened on the client side being forwarded to the master at the next sync.
If you see no risk about such an unlikely event, you can keep the sync active.

Especially if you have a central (master) server, which holds every event, the client loses its importance. It can even happen to have the client an empty Arena every time prior to the event and import the desired event into this "fresh" Arena. In this case, it's neither important to keep the sync on, because this Arena will get wiped for the next event.

Again, it's your decision to chose the best approach here, which fits into your business process the best.

**Comment by futaz** [comment]
OK, I see. Thank you very much for your answer!
