### ISSUE TITLE
Erroneous scoresheet creation

### ISSUE THREAD

**Issue by theswix** [unitedworldwrestling/arena-public#29]
**Which application you are experiencing a problem with**
Arena 1.5.72.1

**Describe the bug**
Scorsheets is created in wrong way if the injured athlete brings doctor's approval for the 2nd day. The athlete in question below is number 5, performing in matches 22, 37, 44, 52, 56. In the final ranking he is 3rd with 20 CP.

**To Reproduce**
1. Create the test session.
2. Run the event until, say, 1/4 final and finish there some match with VIN for one of the athletes.
3. Let the winner of that match to become the finalist.
4. Continue running event until the repechage 
5. Change the status of formerly injured athlete from this list item 3 to "accepted" in Athlete's Preferences and save this status.
6. Make sure this athlete appears in the bracket.
7. Start the repechage match with this athlete
8. Print scoresheet (it will state "injured" there instead of just last name and first name)
9. Let this "injured" athlete win the match with, say VFA
10. See errrors in scoresheet after the match result on the printed scoresheet 

**Expected behavior**
2nd day scoresheets for formely injured athlets to be printed without false data in them (score must be 0:0, no winner and victory type printed beforehand)

**Screenshots**
[bracket57.pdf](https://github.com/unitedworldwrestling/arena-public/files/6330709/bracket57.pdf)
[ranking57kg.pdf](https://github.com/unitedworldwrestling/arena-public/files/6330710/ranking57kg.pdf)
[quaterfinal_injured_OK.pdf](https://github.com/unitedworldwrestling/arena-public/files/6330711/quaterfinal_injured_OK.pdf)
<img width="1440" alt="screenshot_athlete_accepted" src="https://user-images.githubusercontent.com/54967199/115138380-f5b6e300-a055-11eb-817d-ec251cf5f2bc.png">
[repechage_injured__NOT_OK.pdf](https://github.com/unitedworldwrestling/arena-public/files/6330713/repechage_injured__NOT_OK.pdf)
<img width="1440" alt="screenshot_injured_athlete_won" src="https://user-images.githubusercontent.com/54967199/115138398-12531b00-a056-11eb-81b2-9fa7feced986.png">

**Additional context**
In fact, I ran into this problem in the championship I wrote about in issue #27 . So I decided to reproduce this bug on clean session. If you need more details about what happened in the championship , feel free to ask, please.

**Comment by csabavirag** [comment]
Thanks for the well detailed explanation of your problem.
This happened because we combine the Athlete's status (set to Injured) with the matches they lost with victory type of 'VIN'. If any of these happened, the wrestler is classified as injured. Thus, at the moment it's not enough to set the Athlete's status back to Active, but match lost be VIN should have been changed to something else. Which does not make sense.
So internally we agreed that we should simply drop the latter criteria (a match lost by VIN) and only rely on the Athlete status.

A fix has been developed to handle this situation and allow administrators to treat a wrestler as "normal" by setting the Athlete's status back to Accepted. It will most likely be part of the next version.
