### ISSUE TITLE
show total number of matches

### ISSUE THREAD

**Issue by mostafaaghayari** [unitedworldwrestling/arena-public#46]
Hello and thank you. Is it possible to always show total number of matches and number of matches left in the Arena software?

**Comment by csabavirag** [comment]
Hi, since the match numbers are generated starting from 1 and in series, that's easy to get the number of matches by checking the match number of the last match.
The remaining matches are available only for the current session, so if it's not the desired report, it will require this feature implemented.

Where would you expect to see these numbers? In a specific report (eg on the Program/Start list PDF), or at the sessions tab (eg. every session could show its completed/total values and there would be an overall total/completed after the last session)?

**Comment by mostafaaghayari** [comment]
Mr. Cs
Hello and thanks, to manage the time in the tournament, it is always necessary to specify the total number of matches and the number of remaining matches, so it seems better to show it as shown in the Arena app if possible. 
![Uploading match numbers.jpg…]()

**Comment by mostafaaghayari** [comment]
Thank you Mr. Csaba.

**Comment by mostafaaghayari** [comment]
Hello Mr. csaba, please check and guide you in relation to numbers # 38
and # 45.

**Comment by mostafaaghayari** [comment]
Hello Mr. csaba, please check and guide with the numbers # 38 and # 45.

‪On Sat, 28 Aug 2021 at 14:00, ‫مصطفی آقایاری‬‎ ***@***.***> wrote:‬

> Hello Mr. csaba, please check and guide you in relation to numbers # 38
> and # 45.
>

**Comment by csabavirag** [comment]
A preview is available in the beta version and will be released as a part of the next version (most likely 1.5.82)
The matches are displayed as (total/open/closed) per session.

![image](https://user-images.githubusercontent.com/10976654/177303427-89ce74dd-e8d8-40f8-a99a-209520f8646c.png)

**Comment by mostafaaghayari** [comment]
Thank you so much

**Comment by csabavirag** [comment]
New version is released. Please upgrade.

**Comment by mostafaaghayari** [comment]
Hello, thank you very much
