### ISSUE TITLE
Results in forfeit dissqualification end of the competition keeps name 

### ISSUE THREAD

**Issue by NumanYayici** [unitedworldwrestling/arena-public#78]
To uww IT team
İn competition program Arena when we enter the much result as a forfeit , disqualification ,injury end of the results keeps name.For much fixture on the screen kepps them as well untıl the competition session ends .School boys sometimes heavy weight has 1 wrestler if then doesn't gives a point in team ranking. 

Kınd Regards
Türkish wrestling 
Numan Yayıcı

**Comment by csabavirag** [comment]
Yeah, that makes no sense to show an athlete who is excluded from ranking (due to Forfeit or disqualification).
A fix is prepared for the next release.

With regards to 1 person per weight category, if you want to include that person in the ranking, I would recommend to add a "dummy" athlete to that category (eg. James Bond from a dummy team). Then generate matches for that weight category too. For the Final1-2 match in this weight category set VFO for the match result. this way James Bond will be excluded from ranking, but the "real" person will get the ranking points for the 1st place.
