### ISSUE TITLE
Scoreboard problem matches from multiple event on the arena server

### ISSUE THREAD

**Issue by prosfygas33** [unitedworldwrestling/arena-public#79]
Hello uww IT Team,
I am facing an issue with the scoreboard application, i cant find how i can assign a specific event to the scoreboard. To explain in it better,
If in my arena server, i have create multiple events , my scoreboard app displays matches from all events from the same mat.
How to set up to scoreboard app to retrieve matches from specific event.

Thanks in advance.

**Comment by csabavirag** [comment]
Hello @prosfygas33,

since the most common way of using Arena is to organise only one event at a time, Scoreboard does not differentiate the matches if those are from multiple events. 

Normally there should be only 1 active event to use with Scoreboard, but can you describe your use case? Why do you have multiple events in Arena with active matches?

**Comment by prosfygas33** [comment]
Hello @csabavirag ,

thanks for your prompt reply,

My use case is that i want to host the Arena in an online server where at the same time, there is the possibility to have multiple wrestling events. Is there any possible way that the scoreboard fetches matches for specific events or there is any other way i can manage to have simultaneously events ?

**Comment by csabavirag** [comment]
To be honest, this is a setup for a brave men :) What about if you lose network connectivity? All your events will stop working (not getting new matches). Or at least those which dropped the network (if the server stays online).
If your goal is to have all your competitions stored within a single Arena instance, but it's not a problem to operate other Arena servers at the place of events, I would recommend to use the Synchronization capability.

However if you want to keep the number of Arena servers (and operators) as minimal as possible and that's why you chose to expose Arena server to the Internet and access this one remotely, at the moment I can't recommend you a solution.

I know, internally we have talked about supporting more than 4 mats in Scoreboard (currently it is limited to Mat A,B,C,D) and that way you would be able to configure events with their unique mat number (eg. Event-#1 would have Mat A,B; Event-#2 would have Mat C,D,E,F; Event-#3 would have Mat G,H,I) and in Scoreboard you should just chose the right mat.
But this feature has not been released and I neither have any timeframe at the moment. :(
Let me follow up and see if I can give you any detail on that.
