### ISSUE TITLE
Matches not updating and no graph being shown in single elimination bracket?

### ISSUE THREAD

**Issue by WilliamChou06** [unitedworldwrestling/arena-public#90]
**Which application you are interested about**
Arena

**Your question**

When printing the bracket I'm not seeing the graph of the matches at the bottom here:
![image](https://user-images.githubusercontent.com/42121272/169080630-53d9b160-37ea-47aa-9a20-bb7735434bce.png)

Using single elimination bracket for this weight class, for 4 athletes, it creates 6 matches, but doesn't create more matches based on the previous winners/losers.

https://user-images.githubusercontent.com/42121272/169081486-15be1938-e870-41ff-b390-d1fee35a6559.mp4

Not sure if this is a bug, or I'm missing some sort of setting? It's not properly creating a single elimination bracket, it's just creating 6 matches and that's it...

**Comment by csabavirag** [comment]
Hello William,

For 5 and less athletes in a weight category Arena organises matches so in called "Nordic" system (according to UWW rules) instead of the Bracket system. This way every athlete must compete with the others and their results will determine the ranking.  As you can see here:
1. Athlete 1 vs. Athlete 2
2. Athlete 1 vs Athlete 3
3. Athlete 1 vs Athlete 4
4. Athlete 2 vs Athlete 4
5. Athlete 2 vs Athlete 3
6. Athlete 3 vs. Athlete 4

Therefore no need for further matches.

Bracket system is only used for 8 and more athletes (6 or 7 athletes will get 2 "Nordic" groups and the best 2 athletes of both group will compete against each other on a "1/2 Final" and "Final 1-2" + "Final 3-4" brackets.

**Comment by WilliamChou06** [comment]
Ah OK got it. Thank you, that makes sense!
